
variables:
  #git 邮箱
  GIT_USEREMAIL: 1442190496@qq.com
  #git 用户名
  GIT_USERNAME: zhanqinghui

# 定义 stages
stages:

  - build_image

# 定义 build_image  job
build_image_job:

  tags: 
    - ENABLE

  stage: build_image

  #指定分支更新进行编译
  only:
    - image-builder_2.0
    #- master

  before_script:
 
    - git config --global user.email "$GIT_USEREMAIL"
    - git config --global user.name "$GIT_USERNAME"

  script:

    #编译镜像 分支  配置文件
    - ./env/ci.sh 

  when: delayed
  start_in: 60 minutes

